name: Common build setup
runs:
  using: "composite"
  steps:
    - name: Git safe directory
      shell: bash
      run: git config --global --add safe.directory "$(pwd)"

    - uses: iffy/install-nim@v5

    - run: nimble --accept refresh
      shell: bash

    - run: nimble install --verbose
      shell: bash

    - name: Install Playdate SDK
      id: playdate
      uses: pd-rs/get-playdate-sdk@0.4
      with:
        version: latest

    - name: print playdate sdk info
      shell: bash
      run: |
        echo "SDK path env: $PLAYDATE_SDK_PATH"
        echo "SDK root out: ${{ steps.playdate.outputs.root }}"
        echo "SDK version: ${{ steps.playdate.outputs.version }}"
        pdc --version # because SDK/bin already in PATH

    - name: Install apt dependencies
      if: runner.os == 'Linux'
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get install -y libpng16-16 gcc-arm-none-eabi
